### ISSUE TITLE
Error building `container-chain-frontier-node`

### ISSUE THREAD

**Issue by AlexD10S** [moondance-labs/tanssi#678] opened 2024-09-10 13:15 UTC
The functionality works as expected in the `main` branch but not in the latest releases (https://github.com/moondance-labs/tanssi/releases). It works on the main branch but not in the latest releases. Am I missing something to run it properly?

I followed the tutorial to build the `container-chain-frontier-node` using` cargo build -p container-chain-frontier-node --release`, but I'm encountering an error:
```
error[E0433]: failed to resolve: use of undeclared crate or module `std`
  --> pallets/xcm-core-buyer/runtime-api/src/lib.rs:30:1
   |
30 | / sp_api::decl_runtime_apis! {
31 | |     pub trait XCMCoreBuyerApi<BlockNumber, ParaId, CollatorPublicKey> where ParaId: parity_scale_codec::Codec, BlockNumber: parity_sca...
32 | |         fn is_core_buying_allowed(para_id: ParaId, collator_public_key: CollatorPublicKey) -> Result<(), BuyingError<BlockNumber>>;
33 | |         fn create_buy_core_unsigned_extrinsic(para_id: ParaId, proof: BuyCoreCollatorProof<CollatorPublicKey>) -> Box<<Block as BlockT...
...  |
36 | |     }
37 | | }
   | |_^ use of undeclared crate or module `std`
   |
```

**Comment by tmpolaczyk** [comment] 2024-09-11 10:50
That's strange, it looks like a problem with the std feature. As a workaround you can try

```
cargo build --release
```

This will build all the binaries so it will take a bit longer, but it should fix the compile error.

**Comment by AlexD10S** [comment] 2024-09-12 07:44
I encountered the same error, even after building all the binaries. I'm not sure what changes caused this, but it works correctly when I try it on the main branch.

**Comment by girazoki** [comment] 2024-09-12 13:31
It's possible that the main branch is a bit further away than the releases and that is why this works

**Comment by girazoki** [comment] 2024-09-12 13:32
In fact the main branch is using the 2407 stable version from polkadot, while our latest release is in v0.1.11. It might be something coming from polkadot-sdk that was fixed already...Our advise as @tmpolaczyk said to build all the binaries

**Comment by tmpolaczyk** [comment] 2024-09-26 15:46
I confirmed that it's fixed in master, closing

**Closed by tmpolaczyk** 2024-09-26 15:46 UTC
