### ISSUE TITLE
Shutdown error: Io

### ISSUE THREAD

**Issue by stakeworks** [moondance-labs/tanssi#499] opened 2024-04-16 07:38 UTC
**2024-04-13 04:42:05** Shutdown error: Io(Os { code: 2, kind: NotFound, message: "No such file or directory" })

2024-04-13 04:42:00 [Container-3001] 💤 Idle (7 peers), best: #1637143 (0x0acd…b914), finalized #1637142 (0xcae6…26b6), ⬇ 0.2kiB/s ⬆ 290.3kiB/s
2024-04-13 04:42:01 [Container-3096] 💤 Idle (6 peers), best: #110482 (0x216c…aa29), finalized #110481 (0x46b9…dd86), ⬇ 1.2kiB/s ⬆ 1.5kiB/s
2024-04-13 04:42:02 [Relaychain] 💤 Idle (18 peers), best: #15063977 (0xaff0…ea50), finalized #15063974 (0x9296…e2dd), ⬇ 30.4kiB/s ⬆ 47.7kiB/s
2024-04-13 04:42:02 [Orchestrator] 💤 Idle (25 peers), best: #1731600 (0xf30e…9159), finalized #1731598 (0x0611…6203), ⬇ 58.1kiB/s ⬆ 72.1kiB/s
2024-04-13 04:42:03 [Orchestrator] Stopping container chain 3001
2024-04-13 04:42:03 [Orchestrator] Stopping container chain 3096
**2024-04-13 04:42:05** Shutdown error: Io(Os { code: 2, kind: NotFound, message: "No such file or directory" })**
2024-04-13 04:42:06 [Relaychain] ✨ Imported #15063978 (0x84eb…1ff2)
2024-04-13 04:42:07 [Relaychain] 💤 Idle (18 peers), best: #15063978 (0x84eb…1ff2), finalized #15063975 (0xa894…33cf), ⬇ 30.3kiB/s ⬆ 41.1kiB/s
2024-04-13 04:42:07 [Orchestrator] 💤 Idle (25 peers), best: #1731600 (0xf30e…9159), finalized #1731599 (0xce20…215f), ⬇ 0.2kiB/s ⬆ 0.2kiB/s

Binary version: tanssi-node 0.5.2-07be0f3e963
Ubuntu: Ubuntu 22.04.4 LTS

**Comment by girazoki** [comment] 2024-04-16 07:43
thank you @stakeworks , this is a duplicate of https://github.com/moondance-labs/tanssi/issues/486. We are aware and we are already thinking of solutions, but the error should not be critical.

Closing for duplicate

**Closed by girazoki** 2024-04-16 07:43 UTC
